# The configuration for the OAuth2 client
app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
logging:
  level:
    org:
      springframework:
        web:
          socket=DEBUG:
        data:
          redis=DEBUG:
  data:
    redis:
      url: redis://default:Fx3RNvVzMILDi6MFJxcj0Z6ufbNv5uNf@redis-14115.c1.asia-northeast1-1.gce.redns.redis-cloud.com:14115
#Redis configuration
