# The configuration for the OAuth2 client
app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
logging:
  level:
    org:
      springframework:
        web:
          socket=DEBUG:
        data:
          redis=DEBUG:
#Redis configuration
